### PR TITLE
[ci] Improve test coverage by improving the test matrix using tox-travis

### PR DESCRIPTION
**Pull request by Djailla**
This will test against every official Django / python version

### CODE REVIEW

**Comment by Djailla** [comment]
Hello @kra3 if you have some time to review this PR :)

**Comment by Djailla** [comment]
@kra3  up ?

**Comment by kra3** [comment]
Hello Bastien,

I was on vacation.
I will have a look at it soon.

**Comment by kra3** [comment]
Thank you for the PR, Bastien & Sorry for the delay in getting to it.

**Pull request merged**
