### PR TITLE
bump version: 1.7.0

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by Djailla** [comment]
@kra3 could you review this and push a new release to PyPi ?

**Comment by Djailla** [comment]
Hello 👋 Any update on the release ? Thanks

**Comment by kra3** [comment]
Will do it before Monday. Trying to automate this also as I won't always have my personal laptop handy.

**Comment by kra3** [comment]
it is released now (manually). 
travis set-up still need some work (not detecting env vars), I will get to that later.

**Pull request merged**
